[package]
org = "ajirthan"
name = "rainier"
version = "0.1.0"
distribution = "2201.13.4"

[build-options]
observabilityIncluded = true

[[platform.java21.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "persist.inmemory-native"
version = "1.6.0"

